### ISSUE TITLE
Piwik 3

### ISSUE THREAD

**Issue by leandropc** [ThaDafinser/Piwik-IntranetGeoIP#28] opened 2016-12-20 00:37 UTC
Hi, are you planning to make this plugin compatible with Piwik 3? I updated too soon :(

regards

**Comment by ThaDafinser** [comment] 2016-12-20 07:12
@leandropc currently not planned. But i will get into when 1 or 2 bugfix releases are out.

**Comment by tehnotronic** [comment] 2016-12-20 15:07
+1 

I also updated to 3.0.0 and saw that now I am missing this useful plugin

**Comment by ThaDafinser** [comment] 2016-12-20 15:27
Have someone tried it out "by hand"? 

I think this plugin won't need many changes (maybe even none)

**Comment by leandropc** [comment] 2016-12-20 15:37
@ThaDafinser how do I do that?

**Comment by tehnotronic** [comment] 2016-12-20 15:57
Do you mean maybe just playing with the required version number?

https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/plugin.json#L13

Yes, we can probably do that and see if there are any errors.

**Comment by leandropc** [comment] 2016-12-20 19:16
I make the change in the plugin.json file and I still getting 

`    "piwik": ">=2.15.0,>3.0.0",`

IntranetGeoIP requiere Piwik <3.0.0-b1.

**Comment by tehnotronic** [comment] 2016-12-20 21:47
Sadly, this is not so simple after all. I managed to change the version requirement and activate the plugin by this manual: http://developer.piwik.org/guides/migrate-piwik-2-to-3 
But it doesn't display subnetwork information, because in [changelog](https://github.com/piwik/piwik/blob/3.x-dev/CHANGELOG.md) we can see that _**Tracker.newVisitorInformation**_ is deprecated and now we should use _dimensions_ to manage the visit data. And here is more about using dimensions: http://developer.piwik.org/guides/dimensions

**Comment by younessadmi** [comment] 2016-12-21 08:18
+1

I updated to 3.0.0 too soon :(

**Comment by ThaDafinser** [comment] 2016-12-21 10:14
Please try out https://github.com/ThaDafinser/Piwik-IntranetGeoIP/pull/29

**Comment by tehnotronic** [comment] 2016-12-21 10:47
#29 is not working for me. As I said previously, the **Tracker.newVisitorInformation** is now deprecated, I managed to get this working with **Live.getAllVisitorDetails**, but this only works for live tab and there must be extra handling for archive data. I guess the most similar plugin with the live and archive functionality might be: 
https://github.com/piwik/piwik/tree/3.x-dev/plugins/Provider

**Comment by tehnotronic** [comment] 2016-12-21 10:57
My modifications in IntranetGeoIP.php are as follows (works only for Live data):

`


    public function registerEvents(){
        return array('Live.getAllVisitorDetails' => 'extendVisitorDetails');
    }

    public function extendVisitorDetails(&$visitor, $details)
    {
        if (! file_exists($this->getDataFilePath())) {
            Log::error('Plugin IntranetGeoIP does not work. File is missing: ' . $this->getDataFilePath());
            return;
        }

        $data = include $this->getDataFilePath();
        if ($data === false) {
            // no data file found
            // @todo ...inform the user/ log something
            Log::error('Plugin IntranetGeoIP does not work. File is missing: ' . $this->getDataFilePath());
            return;
        }
        if(!is_array($data)){
            Log::error('Your data file seems to be not valid. The content is: ' . print_r($data, true) . ', File used: ' . $this->getDataFilePath());
            return;
        }

        $ipBinary = $details['location_ip'];
        $ip = Network\IP::fromBinaryIP($ipBinary);

        foreach ($data as $value) {
            if (isset($value['networks']) && $ip->isInRanges($value['networks']) === true) {
                // values with the same key are not overwritten by right!
                // http://www.php.net/manual/en/language.operators.array.php
                if (isset($value['visitorInfo'])) {
                    $visitor['providerName'] = $value['visitorInfo']['location_provider'];
                    $visitor['countryCode'] = $value['visitorInfo']['location_country'];
                    $visitor['regionCode'] = $value['visitorInfo']['location_region'];
                    $visitor['city'] = $value['visitorInfo']['location_city'];
                    $visitor['latitude'] = $value['visitorInfo']['location_latitude'];
                    $visitor['longitude'] = $value['visitorInfo']['location_longitude'];
                }
                return;
            }
        }

        // if nothing was matched, you can define default values if you want to
        if (isset($data['noMatch']) && isset($data['noMatch']['visitorInfo'])) {
            $visitor['providerName'] = $data['noMatch']['visitorInfo']['location_provider'];
            return;
        }
    }
}
`

**Comment by ThaDafinser** [comment] 2016-12-21 11:05
@tehnotronic i've missread it sry.

Then it seems that we have a **major problem** here...because this plugin is using **existing columns** and i can't find an event in the list to hook in https://developer.piwik.org/api-reference/events

It could be solved with **Dimensions** but this adds new columns, so all the built in reports wont work anymore... https://developer.piwik.org/guides/dimensions
( like i did it here https://github.com/ThaDafinser/Piwik-Ip2Hostname )

Maybe @tsteur got an idea?

**Comment by tsteur** [comment] 2016-12-21 18:02
It should be possible to overwrite how built-in / existing columns work or what data they track. If you want to overwrite eg "log_visit. countryCode" you can create a visit dimension with the column name "countryCode".  There would be no column type defined as it should re-use an existing column from the DB.

**Comment by ThaDafinser** [comment] 2016-12-22 06:31
Thanks a lot - i will give it a try :+1:

**Comment by Fensterbank** [comment] 2017-01-09 15:14
Any news on this?
I updated Piwik already without checking the issues here und your plugin is the major plugin to get the country of internal app users connected via VPN. :(

**Comment by ThaDafinser** [comment] 2017-01-09 15:35
Need to update the PR today...have prepared it local

**Comment by ThaDafinser** [comment] 2017-01-09 17:27
Please CAREFULLY try out https://github.com/ThaDafinser/Piwik-IntranetGeoIP/pull/29/files

**Comment by Fensterbank** [comment] 2017-01-09 18:34
Thanks!
I will try it tomorrow in our environment and give you feedback asap.

**Comment by Fensterbank** [comment] 2017-01-10 08:27
@ThaDafinser At which point are the new files under `/Columns` used?
They aren't referenced in any way in the `IntranetGeoIP.php`.

Do I have to place the folder Columns under the plugin directory `/plugins/IntranetGeoIP/Columns`?
I don't understand yet, how or when the new files are used.

**Comment by ThaDafinser** [comment] 2017-01-10 12:06
@Fensterbank take this link https://github.com/ThaDafinser/Piwik-IntranetGeoIP/tree/feature/piwik3

And download the ZIP and install it to `plugins/IntranetGeoIP`

**Comment by Fensterbank** [comment] 2017-01-10 14:01
Yes, but my question is still there: The code of the `Columns` files **is not used or referenced at any point** in the plugin code.
How does piwik knows, that there is a folder `Columns` with additonal files?

Anyway, I installed your branch code in my installation but had no success.
Visits are tracked, but still no location information.

**Comment by tsteur** [comment] 2017-01-10 20:33
They are picked up by Piwik automatically. It's a convention in Piwik... and it will automatically pick up all columns placed within that folder when a plugin is enabled

**Comment by Fensterbank** [comment] 2017-01-13 08:34
Okay, thanks @tsteur for the response.

After three days in test it's confirmed the version in the current `piwik 3` branch does not work.
Because of this and the broken user API of Piwik 3 we downgraded back to 2.17.1.
Thanks for trying to solve this so fast @ThaDafinser. I will watch it and hope for further updates. 👍

**Comment by ThaDafinser** [comment] 2017-01-13 08:56
I'm waiting for https://github.com/piwik/piwik/issues/6324 to be resolved in piwik `3.0.1` or later for the next update, like mentioned here https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/issues/8#issuecomment-271797606

**Comment by ThaDafinser** [comment] 2017-03-07 08:50
After a while i could get back to this (sorry for the long delay).

I could get it working on a fresh installation, when i remove the column (delete the following file completely) and activate it after that https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/feature/piwik3/Columns/OverwriteProvider.php

The problem is `VisitDimension` itself:
It does only create missing columns, if you copy the files to the plugin directory and activate it.
https://github.com/piwik/piwik/blob/master/core/Plugin/Dimension/VisitDimension.php#L56-L63

What i still don't understand is, that in the `Provider` plugin the `install()` method is triggered when activating (also there is a workaround for this specific column...seems to be a general problem?)
https://github.com/piwik/piwik/blob/3.x-dev/plugins/Provider/Provider.php#L33

@tsteur is there anything planned, to check if a column exists on activation?

**Comment by ThaDafinser** [comment] 2017-03-07 12:49
Those 3 ***plugins should work now with all with `piwik 3`*** :tada: 

I tried them all local on a fresh installation successfull now, so please test them carefully and provide me some feedback!

# Installation
Download the ZIP from GitHub and install it by hand, see https://piwik.org/faq/plugins/faq_21/

## LdapVisitorInfo (requires both plugins)
https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/tree/feature/piwik3
https://github.com/ThaDafinser/Piwik-LdapConnection/tree/feature/piwik3

## Ip2Hostname
https://github.com/ThaDafinser/Piwik-Ip2Hostname/tree/feature/piwik3

## IntranetGeoIp
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/tree/feature/piwik3

**Comment by Fensterbank** [comment] 2017-03-08 11:22
I just tried **IntranetGeoIp** in our environment and can confirm the plugin works great again! 🥇 
Thank you very much for your work!

**Comment by ThaDafinser** [comment] 2017-03-08 12:33
Just released the package - should be soon available over the marketplace!

**Closed by ThaDafinser** 2017-03-08 12:33 UTC

**Comment by thomykay** [comment] 2017-03-13 10:59
Works great! Thanks for making it work again with Piwik 3.
