### ISSUE TITLE
commenting out "nomatch" not working?

### ISSUE THREAD

**Issue by phoob** [ThaDafinser/Piwik-IntranetGeoIP#31] opened 2017-03-13 14:45 UTC
Hello!

According to the README.md, it is possible to comment out the nomatch-block in IntranetGeoIP.data.php, and making this plugin skip handling unmatched IPs (and letting GeoIP) handle those instead. However, that doesn't seem to be working? (using Piwik 3.0.2 and IntranetGeoIP 3.0.0). Am I doing something wrong..?

**Comment by ThaDafinser** [comment] 2017-03-13 15:10
It should work. Maybe the config file itself is broken? (Syntax?)
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/IntranetGeoIP.php#L128-L133

**Comment by phoob** [comment] 2017-03-13 15:30
Hmmm.. didn't quite understand... the known ips that are matched in the file work. It is just that the unmatched ips all get "unknown" locations instead of defaulting to geoip..

**Comment by ThaDafinser** [comment] 2017-03-14 07:06
@phoob can you post your configuration file (with anonymized data if needed).

Guessing what the error could be is hard :wink:

**Comment by phoob** [comment] 2017-03-14 07:13
Sorry, can't send you the file, but here is an example (I haven't changed the file since it worked previously, with the last version of the plugin on Piwik 2.x.x):

`<?php
return [
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_region' => '12',
            'location_city' => 'Oslo',
            'location_latitude' => '51.234567',
            'location_longitude' => '12.345678',
            'location_provider' => 'Oslo office'
        ],
        'networks' => [
            '10.100.0.0/24',
            '10.100.10.0/24'
        ]
    ],
];
`

**Comment by phoob** [comment] 2017-03-14 07:23
I'm treading water here, but it would seem logical to me that the function should return $userInfo at the end instead of [] (if there is no no match-block)...?

**Comment by phoob** [comment] 2017-03-14 07:26
Just FYI: I'm using the plugin on a multisite Piwik installation, which tracks both our company intranet and internet websites.

**Comment by ThaDafinser** [comment] 2017-03-14 09:58
> Sorry, can't send you the file, but here is an example
> I'm treading water here
> which tracks both our company intranet and internet websites.

What you think i can do with such limited information?
I'm waiting now for all informations and a real config used now (anonymized).

**Comment by phoob** [comment] 2017-03-15 06:44
Ok!

```
<?php
/**
 * @author https://github.com/ThaDafinser
 */
return [
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_region' => '12',
            'location_city' => 'Oslo',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_region' => '16',
            'location_city' => 'Trondheim',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_region' => '14',
            'location_city' => 'Stavanger',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_region' => '06',
            'location_city' => 'Hamar',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    // Kjente virksomheter
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    // Lagt til 2015-12-17
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78',
            '12.34.56.78'
        ]
    ],
    // lagt til 2015-12-21
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    // lagt til 2016-01-08
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],

    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    // lagt til 2016-01-23
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
    [
        'visitorInfo' => [
            'location_country' => 'no',
            'location_provider' => 'Some location provider'
        ],
        'networks' => [
            '12.34.56.78'
        ]
    ],
];

```

**Comment by ThaDafinser** [comment] 2017-03-15 07:22
@phoob your config seems to be correct. Also the plugin should be ok.

Maybe the issue is the other GeoIP provider? https://github.com/piwik/piwik/search?utf8=%E2%9C%93&q=unknown+path%3Aplugins%2FUserCountry&type=Code

Did you tried disable this plugin, before reporting?

**Comment by phoob** [comment] 2017-03-15 10:03
Yes, I have tried disabling and reenabling intranetgeoip – when disabled, The GeoIP databases are used (I'm using the PECL extension).

**Comment by phoob** [comment] 2017-03-19 11:51
See above – after I implemented that one change, your plugin is working like clockwork again :)

**Comment by ThaDafinser** [comment] 2017-03-20 06:38
Thank you.
Fixed in https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases/tag/v3.0.1

**Closed by ThaDafinser** 2017-03-20 06:38 UTC
